# Generated by Django 4.2.7 on 2023-12-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_production_preview_dates_alter_production_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='date_of_birth',
            field=models.DateField(default='1899-01-01'),
        ),
    ]
