# Generated by Django 4.2.7 on 2023-12-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_rename_roles_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
