# Generated by Django 4.2.7 on 2023-12-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_alter_role_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stars',
            new_name='Star',
        ),
    ]
