# Generated by Django 4.2.7 on 2023-12-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_rename_stars_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castcrew',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='performance_date',
        ),
        migrations.AddField(
            model_name='castcrew',
            name='end_date',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castcrew',
            name='start_date',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='performance_datetime',
            field=models.DateTimeField(default='1990-01-01 00:00', verbose_name='performance date'),
            preserve_default=False,
        ),
    ]
