# Generated by Django 4.2.7 on 2023-12-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_remove_castcrew_performance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='preview_dates',
            new_name='preview_start_date',
        ),
        migrations.AlterField(
            model_name='show',
            name='year',
            field=models.DateField(verbose_name='Year of Initial Run'),
        ),
    ]
