# Generated by Django 4.2.7 on 2023-12-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_rename_preview_dates_production_preview_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='castcrew',
            name='role_type',
            field=models.CharField(choices=[('cast', 'Cast'), ('crew', 'Crew')], default='cast', max_length=10),
            preserve_default=False,
        ),
    ]
