# Generated by Django 5.1.3 on 2024-11-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_feedback_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="place_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="place_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
