# Generated by Django 5.1.3 on 2024-11-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_feedback_place_address_feedback_place_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="artist",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
